# NO BORRAR ESTE ARCHIVO ES EL DEPLOYMENT DE LA APLICACION
name: Build, Push Docker image and Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t gonzagomezp1/makers-challenge-altscore:latest .
        docker push gonzagomezp1/makers-challenge-altscore:latest

    - name: Get Docker image digest
      id: get_digest
      run: echo "DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' gonzagomezp1/makers-challenge-altscore:latest)" >> $GITHUB_ENV

    - name: Logout from Docker Hub
      run: docker logout

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: cantinaucc

    - name: Deploy to Cloud Run
      run: |
        gcloud config set run/region us-central1
        gcloud run deploy makers-challenge-altscore \
          --image ${{ env.DIGEST }} \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated
